// <auto-generated />
namespace E_LPATR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changeDataType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeDataType));
        
        string IMigrationMetadata.Id
        {
            get { return "202003271526032_changeDataType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
